services:
  dynamolike:
    build: .
    ports:
      - "3000:3000"
    networks:
      - dynamolike-network
    deploy:
      mode: replicated
      replicas: ${DYNAMOLIKE_REPLICAS:-1}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: root

  minio:
    image: minio/minio
    command: server --console-address ":9001" /data
    volumes:
      - minio-data:/data
    ports:
      - "9000-9021:9000"
      - "9022-9043:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 30s
    networks:
      - dynamolike-network
    deploy:
      mode: replicated
      replicas: ${MINIO_REPLICAS:-2}

volumes:
  minio-data:

networks:
  dynamolike-network:
    name: dynamolike-network
    driver: bridge